### ISSUE TITLE
add CLI?

### ISSUE THREAD

**Issue by scalp42** [stackus/dotenv#1]
HI @stackus 

Thanks for the project. I was wondering if by any chance you could support CLI approach?

Let me know, thank you 🙌

**Comment by stackus** [comment]
It may be possible. What would a CLI approach entail in your mind? Or do you have an example?

**Comment by evandam** [comment]
Hey @stackus, I'd love to see a CLI that looks something like this:

```
dotenv -f .env -f .env.development -f .env.development.local -- ./mycmd
```

Ideally it would be able to load in however many .env files, skipping any that don't exist.

Thanks!

**Comment by stackus** [comment]
A CLI has been added.

See [CLI Instructions](https://github.com/stackus/dotenv#cli) in the README.md for more information.
